FROM geerlingguy/docker-ubuntu2204-ansible:latest

# Instala todas as dependências que o playbook tentaria instalar
RUN apt-get update && \
    apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common \
        python3-pip \
        git \
        gpg \
    && ansible-galaxy collection install community.docker --force \
    && pip3 install docker \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /test

COPY . .

CMD ["ansible-playbook", "-i", "localhost,", "-c", "local", "playbook.yml"]