FROM geerlingguy/docker-ubuntu2204-ansible:latest

# Instala coleção community.docker
RUN ansible-galaxy collection install community.docker

WORKDIR /test
COPY . .

# Prepara inventário local
RUN echo "localhost ansible_connection=local" > /etc/ansible/hosts

# O playbook será executado como entrypoint
ENTRYPOINT ["ansible-playbook", "-i", "localhost,", "-c", "local", "playbook.yml"]